Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = false
  #config.vm.network "forwarded_port", guest: 8080, host: 8888
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.define "jenkins-server-cont-01"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
    vb.gui = true
    vb.name = "jenkins-server-cont-01"
  end

  config.vm.provision "shell", path: "install-jenkins.sh"
end
