Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = false
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.define "jenkins-server01"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
    vb.gui = false
    vb.name = "jenkins-server01"
  end
  
  # config.vm.provision "ansible" do |ansible|
  #   ansible.version = "2.9.6"
  #   ansible.playbook = ""
  # end

  config.vm.provision "shell", path: "install-jenkins.sh"
  # TODO: add to shell provisioner script
  # mkdir ~/.ssh; cd ~/.ssh/ && ssh-keygen -t rsa -m PEM -C "Jenkins agent key" -f "jenkinsAgent_rsa"
end
